---
title: "Cultural Accelerator"
author: Arturo Tha Cuban
---
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Arturo is a front-line anti-racism activist, essayist, and upcoming author; advocating for equality, justice, and accountability.

# social links
twitter_username: @ExtremeArturo
github_username:  ExtremeArturo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
